name = "SPEFiles"
uuid = "ed854f67-b1dc-40c1-a595-92080aa32ec0"
authors = ["Hugo Levy-Falk <hugo.levy-falk@universite-paris-saclay.fr> and contributors"]
version = "0.1.0"

[deps]
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
